# FishType.create(name: 'Silver Carp', min_points: 100, max_points: 200)
# FishType.create(name: 'Salmon', min_points: 200, max_points: 300)
# FishType.create(name: 'Sea Bass', min_points: 300, max_points: 400)
# FishType.create(name: 'Trout', min_points: 300, max_points: 460)
# FishType.create(name: 'Blobfish', min_points: 450, max_points: 550)
# FishType.create(name: 'Halibut', min_points: 450, max_points: 650)
# FishType.create(name: 'Tuna', min_points: 450, max_points: 700)
# FishType.create(name: 'Flabby Whalefish', min_points: 550, max_points: 730)
# FishType.create(name: 'Sunfish', min_points: 350, max_points: 730)
# FishType.create(name: 'Merlin', min_points: 800, max_points: 930)

# Location.create(name: 'Crystal Lake')
# Location.create(name: 'Salt Water Swamp')
# Location.create(name: 'Open Ocean')
# Location.create(name: 'Murky Meadows')

# FishLocation.create(fish_type_id: 1, location_id: 1, fish_count: 80)
# FishLocation.create(fish_type_id: 2, location_id: 1, fish_count: 75)
# FishLocation.create(fish_type_id: 3, location_id: 1, fish_count: 50)
# FishLocation.create(fish_type_id: 4, location_id: 1, fish_count: 40)
# FishLocation.create(fish_type_id: 5, location_id: 1, fish_count: 30)
# FishLocation.create(fish_type_id: 6, location_id: 1, fish_count: 25)
# FishLocation.create(fish_type_id: 7, location_id: 1, fish_count: 20)
# FishLocation.create(fish_type_id: 8, location_id: 1, fish_count: 10)
# FishLocation.create(fish_type_id: 9, location_id: 1, fish_count: 5)
# FishLocation.create(fish_type_id: 10, location_id: 1, fish_count: 2)
